server:
  port: 0

spring:
  application:
    name: store-account
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/store}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
